name: Build App

on:
  workflow_dispatch:
  push:
    tags:
      - "*"

env:
  DOCKER_BUILDKIT: 1

jobs:
  build_image:
    name: Build Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install buildx
        uses: docker/setup-buildx-action@v2
        with:
          config: .github/buildkit.toml

      - name: Login to Docker
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Image Name
        id: imagename
        run: echo "name=ghcr.io/divyam234/teldrive/client" >> $GITHUB_OUTPUT

      - name: Build Next Image
        uses: docker/build-push-action@v3
        with:
          context: ./
          pull: true
          push: true
          tags: ${{ steps.imagename.outputs.name }}:latest
